# DX 601 Week 9 Homework

## Introduction

In this homework, you will practice basic operations with vectors and matrices.

## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx500-examples
* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Submission

To submit your homework, take the following steps.

1. Save and commit this notebook.
2. Push your changes to GitHub.
3. Confirm that your changes are visible in GitHub.
4. Delete the codespace to avoid wasting your free quota.

The auto-grading process usually completes within a few minutes of pushing to GitHub, but occasionally can take several minutes to an hour.
If you submit your homework early enough, you may review the auto-grading results and fix any mistakes before the deadline.


## Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [1]:
import math
import sys

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

## Problems

### Problem 1

Set `p1` to the vector from calculating $[0.0, 0.3, 0.65] + [2.2, 6.2, 0.35]$.

In [9]:
# YOUR CHANGES HERE

# Define the vectors as numpy arrays
v1 = np.array([0.0, 0.3, 0.65])
v2 = np.array([2.2, 6.2, 0.35])

# Perform the vector addition
p1 = v1 + v2

In [10]:
p1

array([2.2, 6.5, 1. ])

### Problem 2

Set `p2` to the magnitude of the vector $[1, 3, 6]$?

In [11]:
# YOUR CHANGES HERE

vector = np.array([1, 3, 6])
p2 = np.linalg.norm(vector)

In [12]:
p2

np.float64(6.782329983125268)

### Problem 3

Set `p3` to the magnitude of the vector `q3`.

In [13]:
# DO NOT CHANGE

q3 = np.asarray([5.2, 5.9, 9.1, 4.3, 2.9])
q3

array([5.2, 5.9, 9.1, 4.3, 2.9])

In [14]:
# YOUR CHANGES HERE

p3 = np.linalg.norm(q3)

In [15]:
p3

np.float64(13.098091464026353)

### Problem 4

Set `p4` to the dot product of $[2, 0, 3]$ and $[0, 4, 1]$.

Hint: this should feel like a really easy case to just do in your head.

In [16]:
# YOUR CHANGES HERE

# Define the vectors
vector1 = np.array([2, 0, 3])
vector2 = np.array([0, 4, 1])

# Calculate the dot product
p4 = np.dot(vector1, vector2)

In [17]:
p4

np.int64(3)

### Problem 5

Set `p5` to the element-wise product of `u5` and `v5`.

Hint: the default behavior of mathematical operations on NumPy arrays is to calculate on an element-wise basis.

In [18]:
# DO NOT CHANGE

u5 = np.asarray([5, 5, 5])
u5

array([5, 5, 5])

In [19]:
# DO NOT CHANGE

v5 = np.asarray([1, 6, 2])
v5

array([1, 6, 2])

In [20]:
# YOUR CHANGES HERE

p5 = u5 * v5

In [21]:
p5

array([ 5, 30, 10])

### Problem 6

Set `p6` to the dot product of `u6` and `v6`.

In [23]:
# DO NOT CHANGE

u6 = np.asarray([2.03, 0.40, 1.35, 9.26, 4.23])
u6

array([2.03, 0.4 , 1.35, 9.26, 4.23])

In [25]:
# DO NOT CHANGE

v6 = np.asarray([1.32, 0.96, 2.35, 1.23, 0.25])
v6

array([1.32, 0.96, 2.35, 1.23, 0.25])

In [27]:
# YOUR CHANGES HERE

# Calculate the dot product
p6 = np.dot(u6, v6)

In [28]:
p6

np.float64(18.683400000000002)

### Problem 7

Set `p7` to the cosine similarity of `u7` and `v7`.

In [32]:
# DO NOT CHANGE

u7 = np.asarray([1, 1, 1, 1])
u7

array([1, 1, 1, 1])

In [31]:
# DO NOT CHANGE

v7 = np.asarray([0, 2, 0, 0])
v7

array([0, 2, 0, 0])

In [33]:
# YOUR CHANGES HERE

# Calculate the dot product of u7 and v7
dot_product = np.dot(u7, v7)

# Calculate the L2 norms (magnitudes) of u7 and v7
norm_u7 = np.linalg.norm(u7)
norm_v7 = np.linalg.norm(v7)

# Calculate the cosine similarity
p7 = dot_product / (norm_u7 * norm_v7)

In [34]:
p7

np.float64(0.5)

### Problem 8

Set `p8` to the vector $[x, y]$ corresponding to the polar coordinates $(r, \theta) = (1, 1)$.

In [35]:
# YOUR CHANGES HERE

# Define polar coordinates
r = 1
theta = 1  # theta is in radians by default in numpy's trig functions

# Convert polar coordinates (r, theta) to Cartesian coordinates (x, y)
# x = r * cos(theta)
# y = r * sin(theta)
x = r * np.cos(theta)
y = r * np.sin(theta)

# Set p8 to the vector [x, y]
p8 = np.array([x, y])

In [36]:
p8

array([0.54030231, 0.84147098])

### Problem 9

Set `p9` to the scalar-vector product $3.1 \cdot [1.31, 2.06, 9.56, 1.79]$.

In [38]:
# YOUR CHANGES HERE

# Define the scalar and the vector
scalar = 3.1
vector = np.array([1.31, 2.06, 9.56, 1.79])

# Calculate the scalar-vector product
p9 = scalar * vector

In [39]:
p9

array([ 4.061,  6.386, 29.636,  5.549])

### Problem 10

Set `p10` to be a unit vector in the same direction as $[1.31, 2.13, -0.92]$.


In [40]:
# YOUR CHANGES HERE

# Define the original vector
v = np.array([1.31, 2.13, -0.92])

# Calculate the magnitude (Euclidean norm) of the vector
magnitude_v = np.linalg.norm(v)

# Create the unit vector p10 by dividing the original vector by its magnitude
p10 = v / magnitude_v

In [41]:
p10

array([ 0.49165501,  0.79940853, -0.34528444])

### Problem 11

Set `p11` to be the first of the following vectors that is orthogonal to $[1, 0, 0]$.

* $[1, 1, 1]$
* $[0.5, 1, 1]$
* $[0, 1, 1]$
* $[1, 0, 1]$

In [42]:
v1 = np.array([1, 1, 1])
v2 = np.array([0.5, 1, 1])
v3 = np.array([0, 1, 1])
v4 = np.array([1, 0, 1])

# The vector to check orthogonality against
ortho_target = np.array([1, 0, 0])

# Function to check orthogonality (dot product is zero)
def is_orthogonal(vec1, vec2):
    # Using np.isclose for floating-point comparisons
    return np.isclose(np.dot(vec1, vec2), 0)

# List of vectors to check
vectors = [v1, v2, v3, v4]

# Iterate through the vectors and set p11 to the first orthogonal one
p11 = None
for v in vectors:
    if is_orthogonal(v, ortho_target):
        p11 = v
        break # Stop after the first one is found

In [43]:
p11

array([0, 1, 1])

### Problem 12

Set `p12` to the first vector in the following list which is linearly dependent on the previous vectors.

* $[0, 1, 1]$
* $[0, 0, 1]$
* $[1, 0, 1]$
* $[1, 1, 1]$

In [45]:
# YOUR CHANGES HERE

vectors = [
    np.array([0, 1, 1]),
    np.array([0, 0, 1]),
    np.array([1, 0, 1]),
    np.array([1, 1, 1])
]

def is_linearly_dependent(current_vector, previous_vectors):
    if not previous_vectors:
        return False
    
    matrix = np.array(previous_vectors + [current_vector])
    
    rank_previous = np.linalg.matrix_rank(np.array(previous_vectors))
    rank_with_current = np.linalg.matrix_rank(matrix)
    
    return rank_with_current == rank_previous

p12 = None
previous = []

for v in vectors:
    if is_linearly_dependent(v, previous):
        p12 = v
        break
    previous.append(v)

In [46]:
p12

array([1, 1, 1])

### Problem 13

Set `p13` to the $3 \times 3$ identity matrix.

In [47]:
# YOUR CHANGES HERE

p13 = np.identity(3)

In [48]:
p13

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Problem 14

Set `p14` to the x intercept of the equation $3y + 5x = 2$.

In [49]:
# YOUR CHANGES HERE

p14 = 2/5

In [50]:
p14

0.4

### Problem 15

Given the dictionary of phrases and vectors in `q15`, set `p15` to the phrase (key) whose vector has the highest cosine similarity with $[0.1, 0.5, 0.2]$.

In [51]:
# DO NOT CHANGE

q15 = {
    "cat": [0.1, 0.6, 0.3],
    "dog": [0.2, 0.5, 0.1],
    "elephant": [-0.3, 0.2, 0.5],
    "giraffe": [-0.4, 0.3, -0.1],
    "lion": [0.1, 0.7, 0.2]
}
q15 = {k: np.asarray(v) for k, v in q15.items()}

q15

{'cat': array([0.1, 0.6, 0.3]),
 'dog': array([0.2, 0.5, 0.1]),
 'elephant': array([-0.3,  0.2,  0.5]),
 'giraffe': array([-0.4,  0.3, -0.1]),
 'lion': array([0.1, 0.7, 0.2])}

In [52]:
# YOUR CHANGES HERE

target_vector = np.asarray([0.1, 0.5, 0.2])

max_similarity = -1
p15 = None

for phrase, vector in q15.items():
    similarity = np.dot(vector, target_vector) / (np.linalg.norm(vector) * np.linalg.norm(target_vector))
    if similarity > max_similarity:
        max_similarity = similarity
        p15 = phrase

In [53]:
p15

'cat'

### Problem 16

Rescale the vectors $[2, 0, 0, 0]$ and $[0, 1, 1, 1]$ so that they are orthonormal.

Save the first rescaled vector in `p16a` and the second rescaled vector in `p16b`.

In [54]:
# YOUR CHANGES HERE

v1 = np.array([2, 0, 0, 0])

# Normalize the vector
p16a = v1 / np.linalg.norm(v1)

In [55]:
p16a

array([1., 0., 0., 0.])

In [56]:
# YOUR CHANGES HERE

v2 = np.array([0, 1, 1, 1])

# Normalize the vector
p16b = v2 / np.linalg.norm(v2)

In [57]:
p16b

array([0.        , 0.57735027, 0.57735027, 0.57735027])

### Problem 17

Set `p17` to the result of the matrix multiplication of `x17` by `y17`.

Hint: NumPy has a function for matrix multiplication, and also overrides the Python @ operator.

In [60]:
# DO NOT CHANGE

x17 = np.array([[0.2, 3.1, 0.6], [-2.9, 2.3, 4.2], [3.0, 4.5, 1.7]])
x17

array([[ 0.2,  3.1,  0.6],
       [-2.9,  2.3,  4.2],
       [ 3. ,  4.5,  1.7]])

In [61]:
# DO NOT CHANGE

y17 = np.array([[1, 2, 3], [6, 5, 4], [7, 8, 9]])
y17

array([[1, 2, 3],
       [6, 5, 4],
       [7, 8, 9]])

In [62]:
# YOUR CHANGES HERE

p17 = x17 @ y17

In [63]:
p17

array([[23. , 20.7, 18.4],
       [40.3, 39.3, 38.3],
       [41.9, 42.1, 42.3]])

### Problem 18

Set `p18` to the angle $\theta$ between the vectors in `u18` and `v18`.
Use the measure of the angle in radians, not degrees.

Hint: you can use the cosine similarity to calculate $\mathrm{cos}~\theta$.
The inverse cosine function to recover the measure of the angle is often called the arc cosine, and both the math and NumPy modules use this for their naming.

In [64]:
# DO NOT CHANGE

u18 = np.asarray([0.3, 0.2, 0.9, -0.4])
u18

array([ 0.3,  0.2,  0.9, -0.4])

In [65]:
# DO NOT CHANGE

v18 = np.asarray([-0.1, 0.3, 0.6, -0.2])
v18

array([-0.1,  0.3,  0.6, -0.2])

In [66]:
# YOUR CHANGES HERE

# Calculate the dot product
dot_product = np.dot(u18, v18)

# Calculate the magnitudes of the vectors
magnitude_u18 = np.linalg.norm(u18)
magnitude_v18 = np.linalg.norm(v18)

# Calculate the cosine of the angle
cos_theta = dot_product / (magnitude_u18 * magnitude_v18)

# Calculate the angle in radians
p18 = np.arccos(cos_theta)

In [67]:
p18

np.float64(0.5023368499123664)

### Problem 19

Set `p19` to be the largest magnitude vector from the following list.

* $[0.1, 0.3, 0.9, -0.8]$
* $[0.2, 0.2, 0.7, 0.6]$
* $[-0.2, 0.2, 0.7, -0.6]$
* $[1.0, 1.0, 0.4, 0.5]$

In [68]:
# YOUR CHANGES HERE

vectors = [
    [0.1, 0.3, 0.9, -0.8],
    [0.2, 0.2, 0.7, 0.6],
    [-0.2, 0.2, 0.7, -0.6],
    [1.0, 1.0, 0.4, 0.5]
]

magnitudes = []
for vec in vectors:
    magnitude = np.linalg.norm(vec)  # Calculate L2 norm (magnitude)
    magnitudes.append(magnitude)

# Find the index of the largest magnitude
max_magnitude_index = np.argmax(magnitudes)

# Set p19 to the vector with the largest magnitude
p19 = vectors[max_magnitude_index]

In [69]:
p19

[1.0, 1.0, 0.4, 0.5]

### Problem 20

Set `p20` to $3 \mathbf{x} + 5$ where $x$ is stored in `x20`.

In [70]:
# DO NOT CHANGE

x20 = np.asarray([0.2, 0.5, -0.3, 0.8])

In [71]:
# YOUR CHANGES HERE

p20 = 3 * x20 * 5

In [72]:
p20

array([ 3. ,  7.5, -4.5, 12. ])

### Generative AI Usage

If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the [generative AI policy](https://www.bu.edu/cds-faculty/culture-community/gaia-policy/).
If you did not use any generative AI tools, simply write NONE below.

NONE